# LightSinger Test Configuration for Quick Training

# Data Configuration
data:
  # Audio processing (smaller dimensions)
  sample_rate: 22050
  mel_channels: 80
  fft_size: 1024
  hop_size: 256
  win_size: 1024
  fmin: 0
  fmax: 8000
  max_wav_length: 4096  # Reduced from 8192
  
  # Dataset paths (same as default)
  datasets_root: "./datasets/gin"
  phoneme_cache_path: "./phoneme_cache"
  
  # Dataset splits (same as default)
  train_file: "train_filelist.txt"
  val_file: "val_filelist.txt"
  test_file: "test_filelist.txt"
  
  # Phoneme settings (same as default)
  phoneme_dict_file: "phoneme_dict.json"

# Model Configuration (reduced complexity)
model:
  # Text Encoder (smaller)
  text_encoder:
    n_layers: 2  # Reduced from 4
    n_heads: 2   # Reduced from 4
    hidden_dim: 128  # Reduced from 256
    dropout: 0.1
    
  # Predictors (same structure, smaller dimensions will be inherited)
  predictors:
    duration_predictor:
      kernel_size: 3
      dropout: 0.5
      
    f0_predictor:
      kernel_size: 3
      dropout: 0.5
      
  # Flow Decoder (fewer flows)
  flow_decoder:
    n_flows: 2  # Reduced from 4
    hidden_dim: 128  # Reduced from 256
    kernel_size: 5
    dilation_rate: 1
    
  # Vocoder (HiFi-GAN) - simpler configuration
  vocoder:
    upsample_rates: [8, 8, 2, 2]
    upsample_kernel_sizes: [16, 16, 4, 4]
    resblock_kernel_sizes: [3, 7, 11]
    resblock_dilation_sizes: [[1, 3], [1, 3], [1, 3]]  # Reduced complexity
    
  # Discriminator (same as default)
  discriminator:
    periods: [2, 3, 5, 7, 11]

# Training Configuration (faster training)
training:
  batch_size: 4  # Reduced from 16
  learning_rate: 0.0002
  betas: [0.8, 0.99]
  lr_decay: 0.999
  seed: 1234
  epochs: 10  # Reduced from 1000
  save_every: 1000  # More frequent saving
  eval_every: 1000  # More frequent evaluation
  precision: 16  # Mixed precision training
  clip_grad_norm: 1.0
  
  # Optimizer (same as default)
  optimizer:
    name: "AdamW"
    weight_decay: 0.01
    
  # Scheduler (same as default)
  scheduler:
    name: "ExponentialLR"
    gamma: 0.999
    
  # Loss Weights (same as default)
  loss_weights:
    mel: 45.0
    duration: 1.0
    f0: 1.0
    gan: 1.0
    fm: 2.0

# Logging Configuration (more frequent)
logging:
  log_dir: "./logs"
  audio_samples: 2  # Reduced from 4 to save time